[build] ERROR vs BAIL

diff --git a/util/check-reqs b/util/check-reqs
--- a/util/check-reqs
+++ b/util/check-reqs
@@ -3,7 +3,7 @@
 # ToAruOS Kernel / Userspace
 
 function INFO {
-    echo $1 >&2
+    echo -e "\033[34;1minfo\033[0m $1" >&2
 }
 
 function WARN {
@@ -12,6 +12,9 @@ function WARN {
 
 function ERROR {
     echo -e "\033[31;1merror\033[0m $1" >&2
+}
+
+function BAIL {
     exit 1
 }
 
@@ -21,12 +24,14 @@ if [ -z `which clang` ] ; then
         WARN "Missing gcc"
         if [ -z `which cc` ] ; then
             ERROR "No compiler found"
+            BAIL
         fi
     fi
 fi
 
 if [ -z `which genext2fs` ] ; then
-    WARN "Missing genext2fs"
-    INFO "You can probably get it from a package of the same name."
+    ERROR "Missing genext2fs"
+    INFO  "You can probably get it from a package of the same name."
+    BAIL
 fi
 
