pass triplets to clang for kernel compilation

diff --git a/util/compiler b/util/compiler
--- a/util/compiler
+++ b/util/compiler
@@ -1,9 +1,12 @@
 #!/bin/bash
 
+export CLANG_FORCE_COLOR_DIAGNOSTICS=1
+
 if [[ -n `which clang` ]] ; then
-	echo "clang -fcolor-diagnostics"
-elif [[ -n `which gcc` ]] ; then
-	echo "gcc"
+	echo "clang -ccc-host-triple i686-elf"
+elif [[ -n `which i686-pc-toaru-gcc` ]] ; then
+	echo "i686-pc-toaru-gcc"
 else
-	echo "cc"
+	echo "Error: No usable compiler found." >&2
+	exit 1
 fi
